In [1]:
from __future__ import absolute_import
from __future__ import print_function

import numpy as np
from numpy import genfromtxt

import pandas as pd
from pandas import ExcelWriter
from pandas import ExcelFile
from pandas import read_csv

import csv
import pprint

import tensorflow as tf
from tensorflow import keras 
from tensorflow.keras import layers, models

import keras
#from keras.utils import to_categorical
from pandas import read_csv
from keras.models import Sequential
from keras import layers
#from keras.optimizers import SGD
from keras import regularizers
from keras.models import Sequential
from keras.layers import Dense
#from keras.optimizers import SGD

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

import matplotlib.pyplot as plt
import seaborn as sns
import random
from pprint import pprint

from sklearn.preprocessing import LabelEncoder
import gspread
import pandas as pd
import pickle 
import pywt
import matplotlib.pyplot as plt
from tensorflow.keras import regularizers
#from keras.utils import to_categorical

from time import time
t00 = time()
import os
from tensorflow.keras import layers
from keras.layers import Input, Dense, concatenate
from keras.models import Model

In [2]:
from google.colab import drive

drive.mount("/content/gdrive")

Mounted at /content/gdrive


In [3]:
N_cut = 52

# Aminoacids

# 0 - 4 
DL_Alpha_Alanine_Train = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/DL_Alpha_Alanine_Train.csv", delimiter=',', names=True, dtype=float)
DL_Alpha_Alanine_Test = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/DL_Alpha_Alanine_Test.csv", delimiter=',', names=True, dtype=float)

DL_Aspartic_Acid_Train = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/DL_Aspartic_Acid_Train.csv", delimiter=',', names=True, dtype=float)
DL_Aspartic_Acid_Test = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/DL_Aspartic_Acid_Test.csv", delimiter=',', names=True, dtype=float)

DL_Isoleucine_Train = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/DL_Isoleucine_Train.csv", delimiter=',', names=True, dtype=float)
DL_Isoleucine_Test = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/DL_Isoleucine_Test.csv", delimiter=',', names=True, dtype=float)

DL_Leucine_Train = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/DL_Leucine_Train.csv", delimiter=',', names=True, dtype=float)
DL_Leucine_Test = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/DL_Leucine_Test.csv", delimiter=',', names=True, dtype=float)

DL_Methionine_Train = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/DL_Methionine_Train.csv", delimiter=',', names=True, dtype=float)
DL_Methionine_Test = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/DL_Methionine_Test.csv", delimiter=',', names=True, dtype=float)

# 5 - 9 

DL_Phenylalanine_Train = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/DL_Phenylalanine_Train.csv", delimiter=',', names=True, dtype=float)
DL_Phenylalanine_Test = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/DL_Phenylalanine_Test.csv", delimiter=',', names=True, dtype=float)

DL_Serine_Train = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/DL_Serine_Train.csv", delimiter=',', names=True, dtype=float)
DL_Serine_Test = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/DL_Serine_Test.csv", delimiter=',', names=True, dtype=float)

DL_Threonine_Train = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/DL_Threonine_Train.csv", delimiter=',', names=True, dtype=float)
DL_Threonine_Test = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/DL_Threonine_Test.csv", delimiter=',', names=True, dtype=float)

DL_Tyrosine_Train = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/DL_Tyrosine_Train.csv", delimiter=',', names=True, dtype=float)
DL_Tyrosine_Test = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/DL_Tyrosine_Test.csv", delimiter=',', names=True, dtype=float)

DL_Valine_Train = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/DL_Valine_Train.csv", delimiter=',', names=True, dtype=float)
DL_Valine_Test = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/DL_Valine_Test.csv", delimiter=',', names=True, dtype=float)

# 10 - 14

Glycine_Train = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/Glycine_Train.csv", delimiter=',', names=True, dtype=float)
Glycine_Test = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/Glycine_Test.csv", delimiter=',', names=True, dtype=float)

L_Arginine_HCl_Train = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/L_Arginine_HCl_Train.csv", delimiter=',', names=True, dtype=float)
L_Arginine_HCl_Test = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/L_Arginine_HCl_Test.csv", delimiter=',', names=True, dtype=float)

L_Asparagine_Monohydrate_Train = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/L_Asparagine_Monohydrate_Train.csv", delimiter=',', names=True, dtype=float)
L_Asparagine_Monohydrate_Test = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/L_Asparagine_Monohydrate_Test.csv", delimiter=',', names=True, dtype=float)

L_Cystine_Train = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/L_Cystine_Train.csv", delimiter=',', names=True, dtype=float)
L_Cystine_Test = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/L_Cystine_Test.csv", delimiter=',', names=True, dtype=float)

L_Glutamic_Acid_Train = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/L_Glutamic_Acid_Train.csv", delimiter=',', names=True, dtype=float)
L_Glutamic_Acid_Test = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/L_Glutamic_Acid_Test.csv", delimiter=',', names=True, dtype=float)

# 15 - 19

L_Histidine_HCl_Train = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/L_Histidine_HCl_Train.csv", delimiter=',', names=True, dtype=float)
L_Histidine_HCl_Test = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/L_Histidine_HCl_Test.csv", delimiter=',', names=True, dtype=float)

L_Lysine_HCl_Train = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/L_Lysine_HCl_Train.csv", delimiter=',', names=True, dtype=float)
L_Lysine_HCl_Test = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/L_Lysine_HCl_Test.csv", delimiter=',', names=True, dtype=float)

L_PLUS_Cysteine_HCl_Train = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/L_PLUS_Cysteine_HCl_Train.csv", delimiter=',', names=True, dtype=float)
L_PLUS_Cysteine_HCl_Test = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/L_PLUS_CysteineHydrochloride_Test.csv", delimiter=',', names=True, dtype=float)

L_Proline_Train = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/L_Proline_Train.csv", delimiter=',', names=True, dtype=float)
L_Proline_Test = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/L_Proline_Test.csv", delimiter=',', names=True, dtype=float)

L_Tryptophan_Train = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/L_Tryptophan_Train.csv", delimiter=',', names=True, dtype=float)
L_Tryptophan_Test = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/L_Tryptophan_Test.csv", delimiter=',', names=True, dtype=float)

# Other chemicals
# 20 - 24

Ampicillin_Sodium_Train = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/Ampicillin_Sodium_Train.csv", delimiter=',', names=True, dtype=float)
Ampicillin_Sodium_Test = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/Ampicillin_Sodium_Test.csv", delimiter=',', names=True, dtype=float)

Anthrone_Train = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/Anthrone_Train.csv", delimiter=',', names=True, dtype=float)
Anthrone_Test = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/Anthrone_Test.csv", delimiter=',', names=True, dtype=float)

beta_Estradiol_Train = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/beta_Estradiol_Train.csv", delimiter=',', names=True, dtype=float)
beta_Estradiol_Test = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/beta_Estradiol_Test.csv", delimiter=',', names=True, dtype=float)

CHAPS_Train = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/CHAPS_Train.csv", delimiter=',', names=True, dtype=float)
CHAPS_Test = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/CHAPS_Test.csv", delimiter=',', names=True, dtype=float)

Chloroquine_Train = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/Chloroquine_Train.csv", delimiter=',', names=True, dtype=float)
Chloroquine_Test = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/Chloroquine_Test.csv", delimiter=',', names=True, dtype=float)

# 25 - 29

D_PLUS_Maltose_Monohydrate_Train = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/D_PLUS_Maltose_Monohydrate_Train.csv", delimiter=',', names=True, dtype=float)
D_PLUS_Maltose_Monohydrate_Test = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/D_PLUS_MaltoseMonohydrate_Test.csv", delimiter=',', names=True, dtype=float)

Fluconazole_Train = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/Fluconazole_Train.csv", delimiter=',', names=True, dtype=float)
Fluconazole_Test = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/Fluconazole_Test.csv", delimiter=',', names=True, dtype=float)

Forskolin_Train = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/Forskolin_Train.csv", delimiter=',', names=True, dtype=float)
Forskolin_Test = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/Forskolin_Test.csv", delimiter=',', names=True, dtype=float)

Laminarin_Train = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/Laminarin_Train.csv", delimiter=',', names=True, dtype=float)
Laminarin_Test = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/Laminarin_Test.csv", delimiter=',', names=True, dtype=float)

Lauric_Acid_Train = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/Lauric_Acid_Train.csv", delimiter=',', names=True, dtype=float)
Lauric_Acid_Test = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/Lauric_Acid_Test.csv", delimiter=',', names=True, dtype=float)

# 30 - 34

Methyl_Viologen_Train = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/Methyl_Viologen_Train.csv", delimiter=',', names=True, dtype=float)
Methyl_Viologen_Test = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/Methyl_Viologen_Test.csv", delimiter=',', names=True, dtype=float)

MOPS_Train = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/MOPS_Train.csv", delimiter=',', names=True, dtype=float)
MOPS_Test = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/MOPS_Test.csv", delimiter=',', names=True, dtype=float)

Na_Salt_Train = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/Na_Salt_Train.csv", delimiter=',', names=True, dtype=float)
Na_Salt_Test = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/Na_Salt_Test.csv", delimiter=',', names=True, dtype=float)

Polyvinyl_Pyrrolidone_Train = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/Polyvinyl_Pyrrolidone_Train.csv", delimiter=',', names=True, dtype=float)
Polyvinyl_Pyrrolidone_Test = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/Polyvinyl_Pyrrolidone_Test.csv", delimiter=',', names=True, dtype=float)

Potato_Starch_Train = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/Potato_Starch_Train.csv", delimiter=',', names=True, dtype=float)
Potato_Starch_Test = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/Potato_Starch_Test.csv", delimiter=',', names=True, dtype=float)

# 35 - 39

Progesterone_Train = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/Progesterone_Train.csv", delimiter=',', names=True, dtype=float)
Progesterone_Test = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/Progesterone_Test.csv", delimiter=',', names=True, dtype=float)

Sodium_Deoxycholate_Train = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/Sodium_Deoxycholate_Train.csv", delimiter=',', names=True, dtype=float)
Sodium_Deoxycholate_Test = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/Sodium_Deoxycholate_Test.csv", delimiter=',', names=True, dtype=float)

Sodium_Dodecylsulfate_Train = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/Sodium_Dodecylsulfate_Train.csv", delimiter=',', names=True, dtype=float)
Sodium_Dodecylsulfate_Test = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/Sodium_Dodecylsulfate_Test.csv", delimiter=',', names=True, dtype=float)

Uridine_Train = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/Uridine_Train.csv", delimiter=',', names=True, dtype=float)
Uridine_Test = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/Uridine_Test.csv", delimiter=',', names=True, dtype=float)

Silver_Nitrate_Train = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/Silver_Nitrate_Train.csv", delimiter=',', names=True, dtype=float)
Silver_Nitrate_Test = genfromtxt("/content/gdrive/MyDrive/6_21_2021_run/Silver_Nitrate_Test.csv", delimiter=',', names=True, dtype=float)

In [4]:
N_cut = 52
N_classes = 40

train_data = np.zeros((N_classes*2500, 1024 - N_cut))
train_label = np.zeros(N_classes*2500)

for i in range(1024 - N_cut - 1):
    for j in range(2500):
        
        # DL_Alpha_Alanine_Train, label 0
        train_data[j][i] = (DL_Alpha_Alanine_Train[i + N_cut][j])
        train_label[j] = 0
        
        # DL_Aspartic_Acid_Train, label 1
        train_data[j + 1*2500][i] = (DL_Aspartic_Acid_Train[i + N_cut][j])
        train_label[j + 1*2500] = 1
        
        # DL_Isoleucine_Train, label 2
        train_data[j + 2*2500][i] = (DL_Isoleucine_Train[i + N_cut][j])
        train_label[j + 2*2500] = 2
        
        # DL_Leucine_Train, label 3
        train_data[j + 3*2500][i] = (DL_Leucine_Train[i + N_cut][j])
        train_label[j + 3*2500] = 3
        
        # DL_Methionine_Train, label 4
        train_data[j + 4*2500][i] = (DL_Methionine_Train[i + N_cut][j])
        train_label[j + 4*2500] = 4
        
        # DL_Phenylalanine_Train, label 5
        train_data[j + 5*2500][i] = (DL_Phenylalanine_Train[i + N_cut][j])
        train_label[j + 5*2500] = 5
        
        # DL_Serine_Train, label 6
        train_data[j + 6*2500][i] = (DL_Serine_Train[i + N_cut][j])
        train_label[j + 6*2500] = 6
        
        # DL_Serine_Train, label 7
        train_data[j + 7*2500][i] = (DL_Threonine_Train[i + N_cut][j])
        train_label[j + 7*2500] = 7
        
        # DL_Tyrosine_Train, label 8
        train_data[j + 8*2500][i] = (DL_Tyrosine_Train[i + N_cut][j])
        train_label[j + 8*2500] = 8
        
        # DL_Valine_Train, label 9
        train_data[j + 9*2500][i] = (DL_Valine_Train[i + N_cut][j])
        train_label[j + 9*2500] = 9
        
        # Glycine_Train, label 10
        train_data[j + 10*2500][i] = (Glycine_Train[i + N_cut][j])
        train_label[j + 10*2500] = 10
        
        # L_Arginine_HCl_Train, label 11
        train_data[j + 11*2500][i] = (L_Arginine_HCl_Train[i + N_cut][j])
        train_label[j + 11*2500] = 11
        
        # L_Asparagine_Monohydrate_Train, label 12
        train_data[j + 12*2500][i] = (L_Asparagine_Monohydrate_Train[i + N_cut][j])
        train_label[j + 12*2500] = 12
        
        # L_Cystine_Train, label 13
        train_data[j + 13*2500][i] = (L_Cystine_Train[i + N_cut][j])
        train_label[j + 13*2500] = 13
        
        # L_Glutamic_Acid_Train, label 14
        train_data[j + 14*2500][i] = (L_Glutamic_Acid_Train[i + N_cut][j])
        train_label[j + 14*2500] = 14
        
        # L_Histidine_HCl_Train, label 15
        train_data[j + 15*2500][i] = (L_Histidine_HCl_Train[i + N_cut][j])
        train_label[j + 15*2500] = 15
        
        # L_Lysine_HCl_Train, label 16
        train_data[j + 16*2500][i] = (L_Lysine_HCl_Train[i + N_cut][j])
        train_label[j + 16*2500] = 16
        
        # L_PLUS_Cysteine_HCl_Train, label 17
        train_data[j + 17*2500][i] = (L_PLUS_Cysteine_HCl_Train[i + N_cut][j])
        train_label[j + 17*2500] = 17
        
        # L_Proline_Train, label 18
        train_data[j + 18*2500][i] = (L_Proline_Train[i + N_cut][j])
        train_label[j + 18*2500] = 18
        
        # L_Tryptophan_Train, label 19
        train_data[j + 19*2500][i] = (L_Tryptophan_Train[i + N_cut][j])
        train_label[j + 19*2500] = 19
        
        # Ampicillin_Sodium_Train, label 20
        train_data[j + 20*2500][i] = (Ampicillin_Sodium_Train[i + N_cut][j])
        train_label[j + 20*2500] = 20
        
        # Anthrone_Train, label 21
        train_data[j + 21*2500][i] = (Anthrone_Train[i + N_cut][j])
        train_label[j + 21*2500] = 21
        
        # beta_Estradiol_Train, label 22
        train_data[j + 22*2500][i] = (beta_Estradiol_Train[i + N_cut][j])
        train_label[j + 22*2500] = 22
        
        # CHAPS_Train, label 23
        train_data[j + 23*2500][i] = (CHAPS_Train[i + N_cut][j])
        train_label[j + 23*2500] = 23
        
        # Chloroquine_Train, label 24
        train_data[j + 24*2500][i] = (Chloroquine_Train[i + N_cut][j])
        train_label[j + 24*2500] = 24
        
        # D_PLUS_Maltose_Monohydrate_Train, label 25
        train_data[j + 25*2500][i] = (D_PLUS_Maltose_Monohydrate_Train[i + N_cut][j])
        train_label[j + 25*2500] = 25
        
        # Fluconazole_Train, label 26
        train_data[j + 26*2500][i] = (Fluconazole_Train[i + N_cut][j])
        train_label[j + 26*2500] = 26
        
        # Forskolin_Train, label 27
        train_data[j + 27*2500][i] = (Forskolin_Train[i + N_cut][j])
        train_label[j + 27*2500] = 27
        
        # Laminarin_Train, label 28
        train_data[j + 28*2500][i] = (Laminarin_Train[i + N_cut][j])
        train_label[j + 28*2500] = 28
        
        # Lauric_Acid_Train, label 29
        train_data[j + 29*2500][i] = (Lauric_Acid_Train[i + N_cut][j])
        train_label[j + 29*2500] = 29
        
        # Methyl_Viologen_Train, label 30
        train_data[j + 30*2500][i] = (Methyl_Viologen_Train[i + N_cut][j])
        train_label[j + 30*2500] = 30
        
        # MOPS_Train, label 31
        train_data[j + 31*2500][i] = (MOPS_Train[i + N_cut][j])
        train_label[j + 31*2500] = 31
        
        # Na_Salt_Train, label 32
        train_data[j + 32*2500][i] = (Na_Salt_Train[i + N_cut][j])
        train_label[j + 32*2500] = 32
        
        # Polyvinyl_Pyrrolidone_Train, label 33
        train_data[j + 33*2500][i] = (Polyvinyl_Pyrrolidone_Train[i + N_cut][j])
        train_label[j + 33*2500] = 33
        
        # Potato_Starch_Train, label 34
        train_data[j + 34*2500][i] = (Potato_Starch_Train[i + N_cut][j])
        train_label[j + 34*2500] = 34
        
        # Progesterone_Train, label 35
        train_data[j + 35*2500][i] = (Progesterone_Train[i + N_cut][j])
        train_label[j + 35*2500] = 35
        
        # Sodium_Deoxycholate_Train, label 36
        train_data[j + 36*2500][i] = (Sodium_Deoxycholate_Train[i + N_cut][j])
        train_label[j + 36*2500] = 36
        
        # Sodium_Dodecylsulfate_Train, label 37
        train_data[j + 37*2500][i] = (Sodium_Dodecylsulfate_Train[i + N_cut][j])
        train_label[j + 37*2500] = 37
        
        # Uridine_Train, label 38
        train_data[j + 38*2500][i] = (Uridine_Train[i + N_cut][j])
        train_label[j + 38*2500] = 38

        # Silver_Nitrate_Train, label 39
        train_data[j + 39*2500][i] = (Silver_Nitrate_Train[i + N_cut][j])
        train_label[j + 39*2500] = 39
        
train_rescaled = np.zeros((N_classes*2500, 1024 - N_cut))
train_maximum = np.zeros(N_classes*2500)
train_minimum = np.zeros(N_classes*2500)

for j in range(1, N_classes*2500):
    train_maximum[j] = np.amin(train_data[j][:])
    train_maximum[j] = np.amax(train_data[j][:])

for i in range(1,1024 - N_cut):
    for j in range(1,N_classes*2500):
        train_rescaled[j][i] = (train_data[j][i] - train_minimum[j])
        train_rescaled[j][i] = train_rescaled[j][i]/(train_maximum[j] - train_minimum[j])

train_rescaled = train_rescaled.reshape((N_classes*2500, 1024 - N_cut, 1))
train_rescaled = train_rescaled.astype('float32')
train_label = train_label.reshape(N_classes*2500)
#train_label = tf.keras.utils.to_categorical(train_label)

test_data = np.zeros((N_classes*500, 1024 - N_cut))
test_label = np.zeros(N_classes*500)

for i in range(1024 - N_cut - 1):
    for j in range(500):

        # DL_Alpha_Alanine_Test, label 0
        test_data[j][i] = (DL_Alpha_Alanine_Test[i + N_cut][j])
        test_label[j] = 0
        
        # DL_Aspartic_Acid_Test, label 1
        test_data[j + 1*500][i] = (DL_Aspartic_Acid_Test[i + N_cut][j])
        test_label[j + 1*500] = 1

        
        # DL_Isoleucine_Test, label 2
        test_data[j + 2*500][i] = (DL_Isoleucine_Test[i + N_cut][j])
        test_label[j + 2*500] = 2
        
        # DL_Leucine_Test, label 3
        test_data[j + 3*500][i] = (DL_Leucine_Test[i + N_cut][j])
        test_label[j + 3*500] = 3
        
        # DL_Methionine_Test, label 4
        test_data[j + 4*500][i] = (DL_Methionine_Test[i + N_cut][j])
        test_label[j + 4*500] = 4
        
        # DL_Phenylalanine_Test, label 5
        test_data[j + 5*500][i] = (DL_Phenylalanine_Test[i + N_cut][j])
        test_label[j + 5*500] = 5
        
        # DL_Serine_Test, label 6
        test_data[j + 6*500][i] = (DL_Serine_Test[i + N_cut][j])
        test_label[j + 6*500] = 6
        
        # DL_Serine_Test, label 7
        test_data[j + 7*500][i] = (DL_Threonine_Test[i + N_cut][j])
        test_label[j + 7*500] = 7
        
        # DL_Tyrosine_Test, label 8
        test_data[j + 8*500][i] = (DL_Tyrosine_Test[i + N_cut][j])
        test_label[j + 8*500] = 8
        
        # DL_Valine_Test, label 9
        test_data[j + 9*500][i] = (DL_Valine_Test[i + N_cut][j])
        test_label[j + 9*500] = 9
        
        # Glycine_Test, label 10
        test_data[j + 10*500][i] = (Glycine_Test[i + N_cut][j])
        test_label[j + 10*500] = 10
        
        # L_Arginine_HCl_Test, label 11
        test_data[j + 11*500][i] = (L_Arginine_HCl_Test[i + N_cut][j])
        test_label[j + 11*500] = 11
        
        # L_Asparagine_Monohydrate_Test, label 12
        test_data[j + 12*500][i] = (L_Asparagine_Monohydrate_Test[i + N_cut][j])
        test_label[j + 12*500] = 12
        
        # L_Cystine_Test, label 13
        test_data[j + 13*500][i] = (L_Cystine_Test[i + N_cut][j])
        test_label[j + 13*500] = 13
        
        # L_Glutamic_Acid_Test, label 14
        test_data[j + 14*500][i] = (L_Glutamic_Acid_Test[i + N_cut][j])
        test_label[j + 14*500] = 14
        
        # L_Histidine_HCl_Test, label 15
        test_data[j + 15*500][i] = (L_Histidine_HCl_Test[i + N_cut][j])
        test_label[j + 15*500] = 15
        
        # L_Lysine_HCl_Test, label 16
        test_data[j + 16*500][i] = (L_Lysine_HCl_Test[i + N_cut][j])
        test_label[j + 16*500] = 16
        
        # L_PLUS_Cysteine_HCl_Test, label 17
        test_data[j + 17*500][i] = (L_PLUS_Cysteine_HCl_Test[i + N_cut][j])
        test_label[j + 17*500] = 17
        
        # L_Proline_Test, label 18
        test_data[j + 18*500][i] = (L_Proline_Test[i + N_cut][j])
        test_label[j + 18*500] = 18
        
        # L_Tryptophan_Test, label 19
        test_data[j + 19*500][i] = (L_Tryptophan_Test[i + N_cut][j])
        test_label[j + 19*500] = 19

        # Ignoring.

        # IGNORE_1
        
        # Ampicillin_Sodium_Test, label 20
        test_data[j + 20*500][i] = (Ampicillin_Sodium_Test[i + N_cut][j])
        test_label[j + 20*500] = 20
        
        # Anthrone_Test, label 21
        test_data[j + 21*500][i] = (Anthrone_Test[i + N_cut][j])
        test_label[j + 21*500] = 21
        
        # IGNORE_2

        # beta_Estradiol_Test, label 22
        test_data[j + 22*500][i] = (beta_Estradiol_Test[i + N_cut][j])
        test_label[j + 22*500] = 22
        
        # IGNORE_3

        # CHAPS_Test, label 23
        test_data[j + 23*500][i] = (CHAPS_Test[i + N_cut][j])
        test_label[j + 23*500] = 23
        
        # Chloroquine_Test, label 24
        test_data[j + 24*500][i] = (Chloroquine_Test[i + N_cut][j])
        test_label[j + 24*500] = 24
        
        # D_PLUS_Maltose_Monohydrate_Test, label 25
        test_data[j + 25*500][i] = (D_PLUS_Maltose_Monohydrate_Test[i + N_cut][j])
        test_label[j + 25*500] = 25
        
        # IGNORE_4

        # Fluconazole_Test, label 26
        test_data[j + 26*500][i] = (Fluconazole_Test[i + N_cut][j])
        test_label[j + 26*500] = 26
        
        # Forskolin_Test, label 27
        test_data[j + 27*500][i] = (Forskolin_Test[i + N_cut][j])
        test_label[j + 27*500] = 27
        
        # Laminarin_Test, label 28
        test_data[j + 28*500][i] = (Laminarin_Test[i + N_cut][j])
        test_label[j + 28*500] = 28
        
        # Lauric_Acid_Test, label 29
        test_data[j + 29*500][i] = (Lauric_Acid_Test[i + N_cut][j])
        test_label[j + 29*500] = 29
        
        # Methyl_Viologen_Test, label 30
        test_data[j + 30*500][i] = (Methyl_Viologen_Test[i + N_cut][j])
        test_label[j + 30*500] = 30
        
        # MOPS_Test, label 31
        test_data[j + 31*500][i] = (MOPS_Test[i + N_cut][j])
        test_label[j + 31*500] = 31
        
        # IGNORE_5

        # Na_Salt_Test, label 32
        test_data[j + 32*500][i] = (Na_Salt_Test[i + N_cut][j])
        test_label[j + 32*500] = 32
        
        # Polyvinyl_Pyrrolidone_Test, label 33
        test_data[j + 33*500][i] = (Polyvinyl_Pyrrolidone_Test[i + N_cut][j])
        test_label[j + 33*500] = 33


        # IGNORE_6

        # Potato_Starch_Test, label 34
        test_data[j + 34*500][i] = (Potato_Starch_Test[i + N_cut][j])
        test_label[j + 34*500] = 34
        
        # Progesterone_Test, label 35
        test_data[j + 35*500][i] = (Progesterone_Test[i + N_cut][j])
        test_label[j + 35*500] = 35
        
        # IGNORE_7

        # Sodium_Deoxycholate_Test, label 36
        test_data[j + 36*500][i] = (Sodium_Deoxycholate_Test[i + N_cut][j])
        test_label[j + 36*500] = 36
        
        # IGNORE_8

        # Sodium_Dodecylsulfate_Test, label 37
        test_data[j + 37*500][i] = (Sodium_Dodecylsulfate_Test[i + N_cut][j])
        test_label[j + 37*500] = 37

        # IGNORE_9
        
        # Uridine_Test, label 38
        test_data[j + 38*500][i] = (Uridine_Test[i + N_cut][j])
        test_label[j + 38*500] = 38

        # IGNORE_10

        # Silver_Nitrate_Test, label 39
        test_data[j + 39*500][i] = (Silver_Nitrate_Test[i + N_cut][j])
        test_label[j + 39*500] = 39

In [5]:
train_rescaled_last = np.ones((N_classes*2500, 1024 - N_cut))
train_minimum = []

for j in range(N_classes*2500):
    train_minimum.append(np.amin(train_data[j][:-1]))

for i in range(1024 - N_cut):
    for j in range(N_classes*2500):
        train_rescaled_last[j][i] = (train_data[j][i] - train_minimum[j])

train_rescaled = np.zeros((N_classes*2500, 1024 - N_cut - 1))

for i in range(1024 - N_cut - 1):
    for j in range(N_classes*2500):
      train_rescaled[j][i] = train_rescaled_last[j][i]

train_maximum = []

for j in range(N_classes*2500):
    train_maximum.append(np.amax(train_rescaled[j][:-1]))
for i in range(1024 - N_cut - 1):
    for j in range(N_classes*2500):
      train_rescaled[j][i] = train_rescaled[j][i]/train_maximum[j]

test_rescaled_last = np.ones((N_classes*500, 1024 - N_cut))
test_minimum = []

for j in range(N_classes*500):
    test_minimum.append(np.amin(test_data[j][:-1]))

for i in range(1024 - N_cut):
    for j in range(N_classes*500):
        test_rescaled_last[j][i] = (test_data[j][i] - test_minimum[j])

test_rescaled = np.zeros((N_classes*500, 1024 - N_cut - 1))

for i in range(1024 - N_cut - 1):
    for j in range(N_classes*500):
      test_rescaled[j][i] = test_rescaled_last[j][i]

test_maximum = []

for j in range(N_classes*500):
    test_maximum.append(np.amax(test_rescaled[j][:-1]))

for i in range(1024 - N_cut - 1):
    for j in range(N_classes*500):
      test_rescaled[j][i] = test_rescaled[j][i]/test_maximum[j]

from sklearn.utils import shuffle
import numpy as np

train_rescaled, train_label = shuffle(train_rescaled, train_label)

test_rescaled = test_rescaled.reshape((N_classes*500, 1024 - N_cut - 1))
test_rescaled = test_rescaled.astype('float32')
test_label = test_label.reshape(N_classes*500)
#test_label = tf.keras.utils.to_categorical(test_label)

print("Rescaling finished")

Rescaling finished


In [6]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(train_rescaled)
X_test = sc.transform(test_rescaled)

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

lda = LDA(n_components=5)
X_train = lda.fit_transform(train_rescaled, train_label)
X_test = lda.transform(test_rescaled)

from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(max_depth=5, random_state=0)

classifier.fit(train_rescaled, train_label)
y_pred1 = classifier.predict(test_rescaled)

from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cm = confusion_matrix(test_label, y_pred1)
print(cm)
print('Accuracy ' + str(accuracy_score(test_label, y_pred1)))

[[173  13   0 ...   0   0   0]
 [  0 500   0 ...   0   0   0]
 [  0   0 497 ...   1   0   0]
 ...
 [  0   0   0 ... 500   0   0]
 [  0   0   0 ...   0 500   0]
 [  0   0   0 ...   0   0 500]]
Accuracy 0.8624
